brew "ripgrep"
brew "fzf"
brew "awscli"
brew "azure-cli"
brew "kubectl"
brew "helm"
brew "podlet"
brew "go"
brew "node"
brew "python@3.12"
brew "lua"
cask "claude-code"
cask "ublue-os/tap/bluefin-wallpapers"
cask "ublue-os/tap/bluefin-wallpapers-extra"
cask "ublue-os/tap/aurora-wallpapers"
cask "ublue-os/tap/bazzite-wallpapers"

