# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

# Container indicator
if grep -qi "kali" /etc/os-release 2>/dev/null; then
    PS1=$'\uf327 '"${PS1}"
elif [ -f /.dockerenv ]; then
    PS1=$'\ue650 '"${PS1}"
elif [ -f /run/.containerenv ]; then
    PS1=$'\ue866 '"${PS1}"
fi

# Starship Config
if command -v starship &>/dev/null; then
    export STARSHIP_CONFIG=$HOME/dotfiles/starship/starship.toml
    eval "$(starship init bash)" >/dev/null 2>&1
fi

# Brew
if [[ -x /var/home/linuxbrew/.linuxbrew/bin/brew ]]; then
    eval "$(/var/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
else
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
